package com.codecool.shop.service;

import com.codecool.shop.dao.ProductCategoryDao;
import com.codecool.shop.dao.ProductDao;
import com.codecool.shop.dao.implementation.CartDaoMem;
import com.codecool.shop.model.Product;
import com.codecool.shop.model.ProductCategory;
import com.codecool.shop.serialization.ProductSerializer;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

public class OrderService {
    private CartDaoMem cartDaoMem;
    private ProductSerializer productSerializer;

    public OrderService() {
        this.cartDaoMem = CartDaoMem.getInstance();
        this.productSerializer = new ProductSerializer();
    }

    public void handlePostProduct(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        //data from API (generated by JavaScript as String)
        String frontData = req.getReader().readLine();
        System.out.println("LOG (OrderService-l30)| Chosen product: "+frontData);
        //convert received String data into Product(object) by ProductSerializer
        Product product = productSerializer.mapFromParams(frontData);
        //add new Product to memory (productDao)
        cartDaoMem.add(product);
        //info do uzytkownia po zamowieniu
    }

    public List<Product> getAllProducts() {
        return cartDaoMem.getAll();
    }

    public double getTotalPrice() {return cartDaoMem.getTotalPrice();}

}
